### ISSUE TITLE
KeyError: 'doc'

### ISSUE THREAD

**Issue by zhouhuhq** [pengpan/91160#11]
Traceback (most recent call last):
  File "/Users/z/Desktop/workspace/health160/91160-master/main.py", line 549, in <module>
    run()
  File "/Users/z/Desktop/workspace/health160/91160-master/main.py", line 515, in run
    init_data()
  File "/Users/z/Desktop/workspace/health160/91160-master/main.py", line 509, in init_data
    set_doctor_configs()
  File "/Users/z/Desktop/workspace/health160/91160-master/main.py", line 447, in set_doctor_configs
    doctors = r.json()["doc"]
KeyError: 'doc'
人多的时候会报这样的错是怎么回事？

**Comment by cyz-lst** [comment]
好像是人多的时候列表加载不出来，就获取不到doc

**Comment by zhouhuhq** [comment]
> 好像是人多的时候列表加载不出来，就获取不到doc

那这个问题应该怎么解决呢？我注释掉了一部分代码，但是会报token过期，然后每次重新登陆都失败

**Comment by cyz-lst** [comment]
token过期那个好像是因为访问太频繁了，IP地址被拉黑了，你改动了他原本的休眠时间吗？那你可能需要加一个代理ip池

**Comment by zhouhuhq** [comment]
> token过期那个好像是因为访问太频繁了，IP地址被拉黑了，你改动了他原本的休眠时间吗？那你可能需要加一个代理ip池

是的，我修改了他的休眠时间，我去试试添加一些功能。谢谢您
