### ISSUE TITLE
你真的用这个挂到了号吗？

### ISSUE THREAD

**Issue by SASUKE40** [pengpan/91160#2]
深圳挂个牙科太难了。

**Comment by pengpan** [comment]
同感，尤其北大的号，所以写了这个脚本，运气好应该是没问题

**Comment by SASUKE40** [comment]
用你这个脚本还是没抢到，555

```
2019-11-07 14:59:52,273 - root - INFO - 努力刷票中...
2019-11-07 15:00:06,384 - root - INFO - 努力刷票中...
2019-11-07 15:00:17,819 - root - INFO - [{'schedule_id': '5dc3beca46e0fb001443ac53', 'unit_id': '21', 'state': '1', 'doctor_id': '200002519', 'doctor_name': '木冬冬', 'to_date': '2019-11-10', 'yuyue_max': '3', 'yuyue_num': '2', 'youzhi_max': '0', 'youzhi_num': '0', 'origin_yuyue_max': '3', 'origin_yuyue_num': '2', 'origin_guahao_max': '0', 'origin_guahao_num': '0', 'left_num': '1', 'dep_id': '4380', 'time_type': 'am', 'time_type_desc': '上午', 'level_name': '主治医师', 'level_code': '102532112', 'his_schedule_id': '270_03_1604_2019-11-10_am', 'guahao_amt': '25', 'y_state': '1', 'y_state_desc': '可预约', 'schext_clinic_label': '', 'registration': '', 'self_paying': '', 'social_security': '', 'schextExtraAmt': '25', 'sch_detl_show': 1}, {'schedule_id': '5dc3bec946e0fb001443ac24', 'unit_id': '21', 'state': '1', 'doctor_id': '200320402', 'doctor_name': 'PY04', 'to_date': '2019-11-10', 'yuyue_max': '3', 'yuyue_num': '2', 'youzhi_max': '0', 'youzhi_num': '0', 'origin_yuyue_max': '3', 'origin_yuyue_num': '2', 'origin_guahao_max': '0', 'origin_guahao_num': '0', 'left_num': '1', 'dep_id': '4380', 'time_type': 'am', 'time_type_desc': '上午', 'level_name': '主治医师', 'level_code': '102532112', 'his_schedule_id': '270_03_PY04_2019-11-10_am', 'guahao_amt': '25', 'y_state': '1', 'y_state_desc': '可预约', 'schext_clinic_label': '', 'registration': '', 'self_paying': '', 'social_security': '', 'schextExtraAmt': '25', 'sch_detl_show': 1}, {'schedule_id': '5dc3bec946e0fb001443ac40', 'unit_id': '21', 'state': '1', 'doctor_id': '200379619', 'doctor_name': '李野', 'to_date': '2019-11-10', 'yuyue_max': '5', 'yuyue_num': '1', 'youzhi_max': '0', 'youzhi_num': '0', 'origin_yuyue_max': '5', 'origin_yuyue_num': '1', 'origin_guahao_max': '0', 'origin_guahao_num': '0', 'left_num': '4', 'dep_id': '4380', 'time_type': 'am', 'time_type_desc': '上午', 'level_name': '住院医师', 'level_code': '102532116', 'his_schedule_id': '270_03_8656_2019-11-10_am', 'guahao_amt': '25', 'y_state': '1', 'y_state_desc': '可预约', 'schext_clinic_label': '', 'registration': '', 'self_paying': '', 'social_security': '', 'schextExtraAmt': '25', 'sch_detl_show': 1}, {'schedule_id': '5dc3bec946e0fb001443ac2e', 'unit_id': '21', 'state': '1', 'doctor_id': '200320355', 'doctor_name': 'PY05', 'to_date': '2019-11-10', 'yuyue_max': '4', 'yuyue_num': '0', 'youzhi_max': '0', 'youzhi_num': '0', 'origin_yuyue_max': '4', 'origin_yuyue_num': '0', 'origin_guahao_max': '0', 'origin_guahao_num': '0', 'left_num': '4', 'dep_id': '4380', 'time_type': 'am', 'time_type_desc': '上午', 'level_name': '主治医师', 'level_code': '102532112', 'his_schedule_id': '270_03_PY05_2019-11-10_am', 'guahao_amt': '25', 'y_state': '1', 'y_state_desc': '可预约', 'schext_clinic_label': '', 'registration': '', 'self_paying': '', 'social_security': '', 'schextExtraAmt': '25', 'sch_detl_show': 1}]
2019-11-07 15:00:17,821 - root - INFO - 刷到票了，开抢了...
Traceback (most recent call last):
  File "main.py", line 358, in <module>
    run()
  File "main.py", line 349, in run
    get_ticket(tickets[0], unit_id, dep_id)
  File "main.py", line 204, in get_ticket
    "detlid": soup.find("ul", id="delts").find("li").attrs["val"],
KeyError: 'val'
```

**Comment by SASUKE40** [comment]
幸运的是，手机抢到了另一个。

**Comment by zeo727** [comment]
hhhh,我也想用这个挂深圳牙科，不过现在挂号提交页面好像改了，现在脚本不能用了

**Comment by pengpan** [comment]
谢谢反馈，我会尽快适配好

**Comment by zeo727** [comment]
谢谢回复，没想到作者居然还在维护，给个小小的建议，希望能增加医生的选项。

**Comment by pengpan** [comment]
可以的，问题不大

**Comment by seryte** [comment]
> 用你这个脚本还是没抢到，555
> 
> ```
> 2019-11-07 14:59:52,273 - root - INFO - 努力刷票中...
> 2019-11-07 15:00:06,384 - root - INFO - 努力刷票中...
> 2019-11-07 15:00:17,819 - root - INFO - [{'schedule_id': '5dc3beca46e0fb001443ac53', 'unit_id': '21', 'state': '1', 'doctor_id': '200002519', 'doctor_name': '木冬冬', 'to_date': '2019-11-10', 'yuyue_max': '3', 'yuyue_num': '2', 'youzhi_max': '0', 'youzhi_num': '0', 'origin_yuyue_max': '3', 'origin_yuyue_num': '2', 'origin_guahao_max': '0', 'origin_guahao_num': '0', 'left_num': '1', 'dep_id': '4380', 'time_type': 'am', 'time_type_desc': '上午', 'level_name': '主治医师', 'level_code': '102532112', 'his_schedule_id': '270_03_1604_2019-11-10_am', 'guahao_amt': '25', 'y_state': '1', 'y_state_desc': '可预约', 'schext_clinic_label': '', 'registration': '', 'self_paying': '', 'social_security': '', 'schextExtraAmt': '25', 'sch_detl_show': 1}, {'schedule_id': '5dc3bec946e0fb001443ac24', 'unit_id': '21', 'state': '1', 'doctor_id': '200320402', 'doctor_name': 'PY04', 'to_date': '2019-11-10', 'yuyue_max': '3', 'yuyue_num': '2', 'youzhi_max': '0', 'youzhi_num': '0', 'origin_yuyue_max': '3', 'origin_yuyue_num': '2', 'origin_guahao_max': '0', 'origin_guahao_num': '0', 'left_num': '1', 'dep_id': '4380', 'time_type': 'am', 'time_type_desc': '上午', 'level_name': '主治医师', 'level_code': '102532112', 'his_schedule_id': '270_03_PY04_2019-11-10_am', 'guahao_amt': '25', 'y_state': '1', 'y_state_desc': '可预约', 'schext_clinic_label': '', 'registration': '', 'self_paying': '', 'social_security': '', 'schextExtraAmt': '25', 'sch_detl_show': 1}, {'schedule_id': '5dc3bec946e0fb001443ac40', 'unit_id': '21', 'state': '1', 'doctor_id': '200379619', 'doctor_name': '李野', 'to_date': '2019-11-10', 'yuyue_max': '5', 'yuyue_num': '1', 'youzhi_max': '0', 'youzhi_num': '0', 'origin_yuyue_max': '5', 'origin_yuyue_num': '1', 'origin_guahao_max': '0', 'origin_guahao_num': '0', 'left_num': '4', 'dep_id': '4380', 'time_type': 'am', 'time_type_desc': '上午', 'level_name': '住院医师', 'level_code': '102532116', 'his_schedule_id': '270_03_8656_2019-11-10_am', 'guahao_amt': '25', 'y_state': '1', 'y_state_desc': '可预约', 'schext_clinic_label': '', 'registration': '', 'self_paying': '', 'social_security': '', 'schextExtraAmt': '25', 'sch_detl_show': 1}, {'schedule_id': '5dc3bec946e0fb001443ac2e', 'unit_id': '21', 'state': '1', 'doctor_id': '200320355', 'doctor_name': 'PY05', 'to_date': '2019-11-10', 'yuyue_max': '4', 'yuyue_num': '0', 'youzhi_max': '0', 'youzhi_num': '0', 'origin_yuyue_max': '4', 'origin_yuyue_num': '0', 'origin_guahao_max': '0', 'origin_guahao_num': '0', 'left_num': '4', 'dep_id': '4380', 'time_type': 'am', 'time_type_desc': '上午', 'level_name': '主治医师', 'level_code': '102532112', 'his_schedule_id': '270_03_PY05_2019-11-10_am', 'guahao_amt': '25', 'y_state': '1', 'y_state_desc': '可预约', 'schext_clinic_label': '', 'registration': '', 'self_paying': '', 'social_security': '', 'schextExtraAmt': '25', 'sch_detl_show': 1}]
> 2019-11-07 15:00:17,821 - root - INFO - 刷到票了，开抢了...
> Traceback (most recent call last):
>   File "main.py", line 358, in <module>
>     run()
>   File "main.py", line 349, in run
>     get_ticket(tickets[0], unit_id, dep_id)
>   File "main.py", line 204, in get_ticket
>     "detlid": soup.find("ul", id="delts").find("li").attrs["val"],
> KeyError: 'val'
> ```

@pengpan 老哥，这个问题还有，下单关键时刻啊😂
